# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github

have_fun: true
code_review:
  pull_request_opened:
    help: false
    summary: false
    code_review: true
    include_drafts: false
